# Generated by devforge. Do not edit.
# Edit the specs under inst/params/ and run devforge::forge_params().

# parameter checkers -----------------------------------------------------------

#' Check node2vec parameters
#'
#' @description Checkmate extension for the output of [params_genewalk()] and
#' [params_node2vec()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkNode2VecParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "p",
      "q",
      "walks_per_node",
      "walk_length",
      "num_workers",
      "batch_size",
      "n_epochs",
      "n_negatives",
      "window_size",
      "lr"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      p = "N1",
      q = "N1",
      walks_per_node = "I1",
      walk_length = "I1",
      num_workers = "I1",
      batch_size = "I1",
      n_epochs = "I1",
      n_negatives = "I1",
      window_size = "I1",
      lr = "N1"
    ),
    label = "node2vec parameters"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert node2vec parameters
#'
#' @inheritParams checkNode2VecParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertNode2VecParams <- checkmate::makeAssertionFunction(checkNode2VecParams)

#' Check GeneWalk data parameters
#'
#' @description Checkmate extension for the output of [params_genewalk_data()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkGeneWalkDataParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "n_signal_genes",
      "n_noise_genes",
      "n_roots",
      "depth",
      "branching",
      "p_lateral",
      "p_ppi",
      "min_annotations",
      "max_annotations",
      "min_noise_subtrees"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      n_signal_genes = "I1",
      n_noise_genes = "I1",
      n_roots = "I1",
      depth = "I1",
      branching = "I1",
      p_lateral = "N1",
      p_ppi = "N1",
      min_annotations = "I1",
      max_annotations = "I1",
      min_noise_subtrees = "I1"
    ),
    label = "GeneWalk data parameters"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert GeneWalk data parameters
#'
#' @inheritParams checkGeneWalkDataParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertGeneWalkDataParams <- checkmate::makeAssertionFunction(
  checkGeneWalkDataParams
)

#' Check kernel parameters
#'
#' @description Checkmate extension for the output of [params_kernel()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkKernelParams <- function(x) {
  res <- check_list_shape(x, c("sigma2", "add_diag", "a", "p"))
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      sigma2 = "N1",
      add_diag = "N1",
      a = "N1",
      p = "I1"
    ),
    label = "kernel parameters"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  if (x$a < 2) {
    return("Parameter `a` must be >= 2 for the pstep kernel.")
  }
  if (x$p < 1L) {
    return("Parameter `p` must be a positive integer.")
  }

  return(TRUE)
}

#' Assert kernel parameters
#'
#' @inheritParams checkKernelParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertKernelParams <- checkmate::makeAssertionFunction(checkKernelParams)

#' Check metapath2vec parameters
#'
#' @description Checkmate extension for the output of [params_metapath2vec()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkMetapath2VecParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "walks_per_node",
      "walk_length",
      "num_workers",
      "n_epochs",
      "n_negatives",
      "window_size",
      "lr",
      "sample"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      walks_per_node = "I1[1,)",
      walk_length = "I1[2,)",
      num_workers = "I1[1,)",
      n_epochs = "I1[1,)",
      n_negatives = "I1[1,)",
      window_size = "I1[1,)",
      lr = "N1(0,)",
      sample = "N1[0,)"
    ),
    label = "metapath2vec parameters"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert metapath2vec parameters
#'
#' @inheritParams checkMetapath2VecParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertMetapath2VecParams <- checkmate::makeAssertionFunction(
  checkMetapath2VecParams
)
