# classes ----------------------------------------------------------------------

## genewalkR class -------------------------------------------------------------

#' genewalkR
#'
#' @description
#' Class that stores keeps all of the important data for the Gene Walk
#' algorithm, see Ietswaart, et al. The class can be subsequently used for to
#' apply the Gene Walk algorithm.
#'
#' @section Properties:
#' \describe{
#'   \item{graph_dt}{A data.table that contains the initial graph.}
#'   \item{embd}{The initial embedding matrix generated by node2vec on top of
#'   the graph.}
#'   \item{permuted_embd}{A list containing the permuted versions of the graph
#'   data for subsequent statistical testing.}
#'   \item{global_stats}{A data.table containing the global statistics with the
#'   FDR correction applied across all gene-pathway pairs.}
#'   \item{gene_stats}{A data.table containing the gene-based statistics with
#'   the FDR correction applied within a given gene.}
#'   \item{params}{A (nested) list that will store all the parameters of the
#'   applied function.}
#' }
#'
#' @return Returns the initialised genewalkR_class object for subsequent
#' analysis.
#'
#' @export
#'
#' @references Ietswaart, et al., Genome Biol, 2021
genewalkR_class <- S7::new_class(
  # name
  name = "genewalkR_class",
  # properties
  properties = list(
    graph_dt = S7::class_data.frame,
    embd = S7::class_numeric,
    permuted_embd = S7::class_list,
    stats = S7::class_data.frame,
    params = S7::class_list
  ),
  # constructor
  constructor = function(graph_dt, graph_gene_params) {
    # checks
    checkmate::assertDataTable(graph_dt)
    checkmate::assertNames(names(graph_dt), must.include = c("from", "to"))
    checkmate::assertList(graph_gene_params)

    params <- list("graph_gene" = graph_gene_params)
    empty_emb <- matrix()
    storage.mode(empty_emb) <- "numeric"

    # need to add empty objects for S7 to behave
    S7::new_object(
      S7::S7_object(),
      graph_dt = graph_dt,
      embd = empty_emb,
      permuted_embd = list(),
      stats = data.table(),
      params = params
    )
  }
)

## getters ---------------------------------------------------------------------

# TODO
