# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_genewalkR_wrappers", use_symbols = TRUE, package_name = "genewalkR")

#' @usage NULL
#' @useDynLib genewalkR, .registration = TRUE
NULL

#' Function that generates the GeneWalk embedding
#'
#' @description Wrapper function that leverages Rust and the Burn Tensor
#' framework to generate node representations for subsequent usage in the
#' GeneWalk approach. The default back end is the torch CPU backend. In the
#' future there might be other backends added, but testing revealed this one
#' to be very performant.
#'
#' @param from Integer vector. The node indices indicating where the edge
#' originates from.
#' @param to Integer vector. The node indices indicating where the edge
#' goes to.
#' @param weights Optional numeric vector. If not supplied, defaults to `1.0`
#' as edge weight.
#' @param gene_walk_params Named list. Contains the parameters for running
#' gene walk.
#' @param embd_dim Integer. Embedding dimension.
#' @param directed Boolean. Is the graph directed. If set to `FALSE` reverse
#' edges will be added.
#' @param seed Integer. For reproducibility of the algorithm.
#' @param verbose Boolean. Controls verbosity of the algorithm.
#'
#' @return A numerical matrix of number nodes x desired embedding dimensios.
#'
#' @export
rs_gene_walk <- function(from, to, weights, gene_walk_params, embd_dim, directed, seed, verbose) .Call(wrap__rs_gene_walk, from, to, weights, gene_walk_params, embd_dim, directed, seed, verbose)

#' Function to generate permuted embeddings
#'
#' @description
#' Wrapper function to generate permuted embeddings and subsequently the
#' null distribution of cosine similarities for statistical testing.
#'
#' @param from Integer vector. The node indices indicating where the edge
#' originates from.
#' @param to Integer vector. The node indices indicating where the edge
#' goes to.
#' @param weights Optional numeric vector. If not supplied, defaults to `1.0`
#' as edge weight.
#' @param gene_walk_params Named list. Contains the parameters for running
#' gene walk.
#' @param n_perm Integer.
#' @param embd_dim Integer. Embedding dimension.
#' @param directed Boolean. Is the graph directed. If set to `FALSE` reverse
#' edges will be added.
#' @param seed Integer. For reproducibility of the algorithm.
#' @param verbose Boolean. Controls verbosity of the algorithm.
#'
#' @returns A list with the null distribution of the cosine similarities per
#' given permutation.
#'
#' @export
rs_gene_walk_perm <- function(from, to, weights, gene_walk_params, n_perm, embd_dim, directed, seed, verbose) .Call(wrap__rs_gene_walk_perm, from, to, weights, gene_walk_params, n_perm, embd_dim, directed, seed, verbose)

#' Calculate the test statistics
#'
#' @description Calculates the test statistic for the gene / pathway pairs.
#'
#' @param gene_embds Matrix of n_genes x their graph embeddings
#' @param pathway_embds Matrix of n_pathways x their graph embeddings
#' @param null_distributions List of null distribution vectors (one per
#' permutation).
#' @param verbose Controls verbosity of the function.
#'
#' @returns A list with vectors:
#' \itemize{
#'   \item gene - Gene indices (1-based for R)
#'   \item pathway - Pathway indices (1-based for R)
#'   \item pval - P-values for each gene-pathway pair
#'   \item global_fdr - FDR corrected across all pairs
#'   \item gene_fdr - FDR corrected within each gene
#' }
#'
#' @export
rs_gene_walk_test <- function(gene_embds, pathway_embds, null_distributions, verbose) .Call(wrap__rs_gene_walk_test, gene_embds, pathway_embds, null_distributions, verbose)

#' Cosine similarity between two vectors
#'
#' @description
#' Rust function to quickly calculate Cosine distances.
#'
#' @param a Numeric vector. Vector a for which to calculate the similarity.
#' @param b Numeric vector. Vector b for which to calculate the similarity.
#'
#' @returns Cosine similarity between the two vectors
#'
#' @export
rs_cosine_sim <- function(a, b) .Call(wrap__rs_cosine_sim, a, b)


# nolint end
