# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_genewalkR_wrappers", use_symbols = TRUE, package_name = "genewalkR")

#' @usage NULL
#' @useDynLib genewalkR, .registration = TRUE
NULL

#' Generate a node2vec embeddings
#'
#' @description Trains node2vec on the original provided graph.
#'
#' @param from Integer vector. Node indices for edge origins.
#' @param to Integer vector. Node indices for edge destinations.
#' @param weights Optional numeric vector. Edge weights, defaults to 1.0.
#' @param node2vec_params Named list. Training parameters (p, q,
#'   walks_per_node, walk_length, num_workers, n_epochs, num_negatives,
#'   window_size, lr, dim).
#' @param embd_dim Integer. Embedding dimension.
#' @param directed Boolean. Treat graph as directed.
#' @param seed Integer. Random seed (incremented per rep).
#' @param verbose Boolean. Controls verbosity.
#'
#' @return An embedding of dimension n_nodes x embedding dim.
#'
#' @export
rs_node2vec <- function(from, to, weights, node2vec_params, embd_dim, directed, seed, verbose) .Call(wrap__rs_node2vec, from, to, weights, node2vec_params, embd_dim, directed, seed, verbose)

#' Generate GeneWalk node embeddings (multiple reps)
#'
#' @description Trains node2vec on the original GeneWalk network `n_graph`
#' times with different random seeds, returning a list of embedding matrices.
#' This provides the variance across embedding reps needed for the final
#' log_stats aggregation.
#'
#' @param from Integer vector. Node indices for edge origins.
#' @param to Integer vector. Node indices for edge destinations.
#' @param weights Optional numeric vector. Edge weights, defaults to 1.0.
#' @param gene_walk_params Named list. Training parameters (p, q,
#'   walks_per_node, walk_length, num_workers, n_epochs, num_negatives,
#'   window_size, lr, dim).
#' @param n_graph Integer. Number of independent embedding reps.
#' @param embd_dim Integer. Embedding dimension.
#' @param directed Boolean. Treat graph as directed.
#' @param seed Integer. Random seed (incremented per rep).
#' @param verbose Boolean. Controls verbosity.
#'
#' @return A list of n_graph numeric matrices, each n_nodes x embedding dim.
#'
#' @export
rs_gene_walk <- function(from, to, weights, gene_walk_params, n_graph, embd_dim, directed, seed, verbose) .Call(wrap__rs_gene_walk, from, to, weights, gene_walk_params, n_graph, embd_dim, directed, seed, verbose)

#' Generate null distributions from degree-matched random networks
#'
#' @description For each permutation, generates a random graph via the
#' configuration model (matching the original degree distribution), trains
#' node2vec on it, then collects cosine similarities between each node and
#' its unique neighbours in the random graph. This matches the original Python
#' GeneWalk procedure.
#'
#' @param from Integer vector. Node indices for edge origins.
#' @param to Integer vector. Node indices for edge destinations.
#' @param weights Optional numeric vector. Edge weights, defaults to 1.0.
#' @param gene_walk_params Named list. Training parameters.
#' @param n_perm Integer. Number of null permutations.
#' @param embd_dim Integer. Embedding dimension.
#' @param directed Boolean. Treat graph as directed.
#' @param seed Integer. Random seed.
#' @param verbose Boolean. Controls verbosity.
#'
#' @returns A list of n_perm numeric vectors of null cosine similarities.
#'
#' @export
rs_gene_walk_perm <- function(from, to, weights, gene_walk_params, n_perm, embd_dim, directed, seed, verbose) .Call(wrap__rs_gene_walk_perm, from, to, weights, gene_walk_params, n_perm, embd_dim, directed, seed, verbose)

#' Calculate GeneWalk test statistics
#'
#' @description Pools all null distributions into one, then for each observed
#' embedding rep: computes p-values, per-gene FDR, and global FDR. Finally
#' aggregates across reps with geometric mean and 95\% CI (log_stats).
#'
#' Matches the paper: "we repeat the above-described network representation
#' learning and significance testing procedures of the GWN nreps_graph times
#' and provide the mean and 95\% confidence intervals".
#'
#' @param gene_embds_list List of n_graph gene embedding matrices
#'   (n_genes x dim).
#' @param pathway_embds_list List of n_graph pathway embedding matrices
#'   (n_pathways x dim).
#' @param null_similarities List of n_perm numeric vectors (null cosine
#'   similarities to be pooled).
#' @param connected_pathways List. Per-gene integer vectors of connected
#'   pathway indices (1-indexed).
#' @param verbose Controls verbosity.
#'
#' @returns A list with per-pair statistics.
#'
#' @export
rs_gene_walk_test <- function(gene_embds_list, pathway_embds_list, null_similarities, connected_pathways, verbose) .Call(wrap__rs_gene_walk_test, gene_embds_list, pathway_embds_list, null_similarities, connected_pathways, verbose)

#' Cosine similarity between two vectors
#'
#' @description Computes cosine similarity between two numeric vectors.
#'
#' @param a Numeric vector.
#' @param b Numeric vector.
#'
#' @returns Cosine similarity between the two vectors.
#'
#' @export
rs_cosine_sim <- function(a, b) .Call(wrap__rs_cosine_sim, a, b)

#' Generate synthetic data for node2vec
#'
#' @param test_data String. One of
#'   c("barbell", "caveman", "stochastic_block").
#' @param n_nodes_per_cluster Integer. Nodes per cluster.
#' @param n_clusters Integer. Number of clusters.
#' @param p_within Numeric. Within-cluster edge probability (0-1).
#' @param p_between Numeric. Between-cluster edge probability (0-1).
#' @param seed Integer. Random seed.
#'
#' @returns A list with edges and nodes.
#'
#' @export
rs_node2vec_synthetic_data <- function(test_data, n_nodes_per_cluster, n_clusters, p_within, p_between, seed) .Call(wrap__rs_node2vec_synthetic_data, test_data, n_nodes_per_cluster, n_clusters, p_within, p_between, seed)

#' Generate synthetic GeneWalk data with controlled signal structure
#'
#' @param n_signal_genes Integer. Genes annotated to a single ontology subtree.
#' @param n_noise_genes Integer. Genes with annotations scattered across
#'   subtrees.
#' @param n_roots Integer. Number of ontology root terms.
#' @param depth Integer. Depth of each ontology subtree.
#' @param branching Integer. Average branching factor per node.
#' @param p_lateral Numeric. Probability of lateral edges within each ontology
#'   level.
#' @param p_ppi Numeric. PPI connection probability within gene groups.
#' @param min_annotations Integer. Minimum annotations per gene.
#' @param max_annotations Integer. Maximum annotations per gene.
#' @param min_noise_subtrees Integer. Minimum number of different subtrees
#'   each noise gene must span.
#' @param seed Integer. Random seed.
#'
#' @returns A list with: ontology_edges, gene_ont_edges, ppi_edges,
#'   signal_genes, noise_genes.
#'
#' @export
rs_build_synthetic_genewalk <- function(n_signal_genes, n_noise_genes, n_roots, depth, branching, p_lateral, p_ppi, min_annotations, max_annotations, min_noise_subtrees, seed) .Call(wrap__rs_build_synthetic_genewalk, n_signal_genes, n_noise_genes, n_roots, depth, branching, p_lateral, p_ppi, min_annotations, max_annotations, min_noise_subtrees, seed)

#' Generate a synthetic differential graph pair for testing context-aware node
#' embeddings
#'
#' Produces two graphs sharing the same backbone but differing in defined
#' regions. Community 1 is a stable negative control, identical across both
#' graphs. Community 2 contains a hub node demoted to a peripheral node in
#' graph 2. Two bridge nodes span communities 2 and 3 in graph 1 but are
#' fully embedded within community 3 in graph 2. Exclusive nodes appear in
#' only one graph.
#'
#' @param n_stable Integer. Number of nodes in the stable negative-control
#'   community.
#' @param n_comm2 Integer. Number of regular nodes in community 2, excluding
#'   the hub.
#' @param n_comm3 Integer. Number of nodes in community 3, excluding bridge
#'   nodes.
#' @param n_exclusive Integer. Number of exclusive nodes in each graph.
#'
#' @return A named list with:
#' `g1_edges` (from, to), `g1_nodes` (node, cluster),
#'   `g2_edges` (from, to), `g2_nodes` (node, cluster), `data_info`
#'   (shared_nodes, is_differential, g1_only, g2_only).
#'
#' @export
rs_differential_graph_data <- function(n_stable, n_comm2, n_comm3, n_exclusive) .Call(wrap__rs_differential_graph_data, n_stable, n_comm2, n_comm3, n_exclusive)

#' Orthogonal Procrustes alignment and cosine similarity scoring
#'
#' Aligns `embd1` onto `embd2` via orthogonal Procrustes (SVD) and returns
#' cosine similarities per node. Both matrices must have identical dimensions
#' and matching row order, i.e. row i in `embd1` corresponds to row i in
#' `embd2`.
#'
#' @param embd1 Numeric matrix. k x d embedding matrix for graph 1.
#' @param embd2 Numeric matrix. k x d embedding matrix for graph 2.
#'
#' @return Named list with `aligned` (k x d matrix, `embd1` rotated onto
#' `embd2`) and `cosine_similarities` (numeric vector of length k).
#'
#' @export
rs_procrustes_align <- function(embd1, embd2) .Call(wrap__rs_procrustes_align, embd1, embd2)


# nolint end
